[package]
name = "presentrs"
version = "0.2.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]
edition = "2018"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
comrak = "0.11"
derive_more = "0.99"
html5ever = "0.25"
markup5ever_arcdom = "0.1"
