[package]
name = "presentrs"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[features]
client = [ "yew" ]
server = [ "actix-web", "failure" ]

[dependencies]
actix-web = { version = "0.6", optional = true }
failure = { version = "0.1", optional = true }
yew = { git = "https://github.com/DenisKolodin/yew", optional = true }
